TEXT_DESCRIPTION = {
    'win_condition': "All tower damage must be done with X.",
    'last_hit': "Destroy at least one tower with X.",
    'arena': "Use a deck containing only cards from these arenas.",
    'duplicate': "Have X cards alive on battlefield at once.",
    'elixir': "Use a deck that has X.* elixir average.",
    'triplet': "Use a deck that contains the three cards."
}

MISC_DESCRIPTION = {
    'Balloon_Special.png': "Deal 5 hits to towers with 1 Balloon.",
    'Bandit_Special.png': "Have one Bandit dash 4 times.",
    'BossBandit_Special.png': "Have one Boss Bandit dash 5 times.",
    'Bowler_Special.png': "Hit 10+ units with 1 Bowler throw.",
    'Buildings.png': "Use a deck only with buildings.",
    'CoC.png': "Use a deck only with Clash Of Clans units.",
    'Commons.png': "Use a deck only with common cards.",
    'Electrics.png': "Use a deck with 6 electric cards.",
    'Epics.png': "Use a deck only with epic cards.",
    'Executioner_Special.png': "Kill all opponent's unit types with one Executioner",
    'Flying.png': "Use a deck only with air troops.",
    'Rares.png': "Use a deck only with rare cards.",
    'Girls.png': "Use a deck only with female cards.",
    'Goblins.png': "Use a deck only with goblin cards.",
    'KingTower.png': "Have only your King Tower alive.",
    'Legendaries.png': "Use a deck with only legendary cards.",
    'LetHimCook.png': "Have a level 18 troop.",
    'LittlePrince_Special.png': "Destroy at least one tower with Guardienne.",
    'Log_Special.png': "Kill a Lumberjack with The Log.",
    'MegaKnight_Special.png': "Have one MK jump 4 times.",
    'Monk_Special.png': "Hit a tower with any Monk deflected spell.",
    'Mother_Special.png': "Have one Mother Witch summon 10 pigs.",
    'MightyMiner_Special.png': "Have one Mighty Miner destroy 2 towers.",
    'PEKKA_Special.png': "Kill a PEKKA with a Mini PEKKA.",
    'Perfection.png': "Win without troops reaching your towers.",
    'Prince_Special.png': "Have one Prince do 3 sprints.",
    'Princess_Special.png': "Have one Princess shoot 10 times.",
    'Tornado_Special.png': "Have Tornado and activate your King Tower.",
    'Random.png': "Use your last oppenent's deck.",
    'Rocket_King_Tower.png': "Rocket the enemy King Tower within 20 seconds.",
    'Skeletons.png': "Use a deck with only skeleton cards.",
    'Space1.png': "Place troops/buildings only on the displayed squares.",
    'Space2.png': "Place troops/buildings only on the displayed squares.",
    'Space3.png': "Place troops/buildings only on the displayed squares.",
    'Space4.png': "Place troops/buildings only on the displayed squares.",
    'Spells.png': "Use a deck with only spell cards.",
    '3Musketeers_Special.png': "Have all 3 Musketeers hit a tower once.",
    'elixir6_7.png': "Use a deck only with 6 or 7 elixir cards.",
    'Xbow_Special.png': "Hit all 3 enemy towers with X-bow.",
}

MODIFIERS_DESCRIPTION = {
    'Cannoner.png': "Use Cannoner as your Tower troop.",
    'DaggerDuchess.png': "Use Dagger Duchess as your Tower troop.",
    'RoyaleChef.png': "Use Royale Chef as your Tower troop.",
    'Emote.png': "Use an emote for each played card.",
    'RedCrown.png': "Let your enemy destroy a tower.",
    'Champion.png': "Have a Champion in your deck.",
    'MegaKnight.png': "Have MK and use it at least once.",
    'Sneaky.png': "Have Golem and use it at least once.",
    '2v2.png': "Play on 2v2.",
    'elixir_3.png': "Use a deck of 3 or less elixir.",
    'elixir_5.png': "Use a deck of 5 or more elixir.",
    'Time.png': "Win without overtime.",
    'TimeTower.png': "Destroy a tower before x2 elixir.",
    'TowerActivation.png': "Activate enemy King Tower within 20 seconds.",
    'TowerActivationSelf.png': "Have Tornado and activate your King Tower.",
    'FullTower.png': "Have one side-tower full HP.",
    '3Crowns.png': "Get three crowns.",
    'Evo.png': "One evolution allowed.",
    'NoSpells.png': "Use a deck with least spells possible.",
    'Rarity.png': "Have at least one card of each rarity.",
    'Damage.png': "All cards able to damage towers must do so.",
    'BarbarianHut.png': "Have Barbarian Hut and place at least three.",
}

INCOMPATIBLE_MODIFIERS = {
        'elixir': ['elixir_5.png', 'elixir_3.png'],
        'Rocket_King_Tower.png': ['TowerActivation.png'],
        'KingTower.png': ['TowerActivation.png', 'RedCrown.png', '3Crowns.png'],
        'Spells.png': ['NoSpells.png'],
        'Perfection.png': ['RedCrown.png', 'TowerActivationSelf.png'],
        'Buildings.png': ['Rarity.png', 'elixir_5.png', 'elixir_3.png', 'NoSpells.png', 'TowerActivationSelf.png'],
        'arena': ['elixir_3.png', 'elixir_5.png', 'Rarity.png'],
        'Random.png': ['elixir_5.png', 'elixir_3.png', 'NoSpells.png'],
        'LetHimCook.png': ['RoyaleChef.png'],
        'Monk.png': ['Champion.png'],
        'BossBandit.png': ['Champion.png'],
        'Goblinstein.png': ['Champion.png'],
        'LittlePrince.png': ['Champion.png'],
        'ArcherQueen.png': ['Champion.png'],
        'GoldenKnight.png': ['Champion.png'],
        'MightyMiner.png': ['Champion.png'],
        'SkeletonKing.png': ['Champion.png'],
        'BossBandit_Special.png': ['Champion.png'],
        'Monk_Special.png': ['Champion.png'],
        'MightyMiner_Special.png': ['Champion.png'],
        'LittlePrince_Special.png': ['Champion.png'],
        'Golem.png': ['Sneaky.png'],
        'Tornado_Special.png': ['TowerActivationSelf.png'],
        'elixir6_7.png': ['elixir_3.png'],
        'Commons.png': ['Rarity.png'],
        'Rares.png': ['Rarity.png'],
        'Epics.png': ['Rarity.png'],
        'Legendaries.png': ['Rarity.png'],
        'BarbarianHut.png': ['BarbarianHut.png']
    }

TRIPLETS_LIST = [
    ["ElectroSprit.png", "FireSpirit.png", "IceSpirit.png"],
    ["GoblinDrill.png", "Miner.png", "WallBreakers.png"],
    ["GoblinGang.png", "SkeletonArmy.png", "MinionHorde.png"],
    ["BabyDragon.png", "InfernoDragon.png", "ElectroDragon.png"],
    ["Rocket.png", "Fireball.png", "Poison.png"],
    ["Giant.png", "ElectroGiant.png", "RoyaleGiant.png"],
    ["Golem.png", "ElixirGolem.png", "IceGolem.png"],
    ["Mirror.png", "GiantBomber.png", "Clone.png"],
    ["HogRider.png", "RamRider.png", "BattleRam.png"],
    ["ElixirCollector.png", "ElixirGolem.png", "Rage.png"],
    ["DarkPrince.png", "LittlePrince.png", "Prince.png"],
    ["Wizard.png", "ElectroWizard.png", "IceWizard.png"],
    ["Valkyrie.png", "RuneGiant.png", "Berserker.png"],
    ["BombTower.png", "Balloon.png", "Bomber.png"],
    ["Bandit.png", "BossBandit.png", "Rascals.png"],
    ["Zappies.png", "Sparky.png", "Tesla.png"],
    ["RoyaleGhost.png", "SpiritEmpress.png", "Graveyard.png"],
    ["MotherWitch.png", "Witch.png", "NightWitch.png"],
    ["Cannon.png", "FlyingMachine.png", "CannonCart.png"],
    ["Fireball.png", "Earthquake.png", "Tornado.png"],
    ["Void.png", "Vines.png", "GoblinCurse.png"],
    ["Knight.png", "GoldenKnight.png", "MegaKnight.png"],
    ["Archer.png", "ArcherQueen.png", "Arrows.png"],
    ["Barbarians.png", "BarbarianHut.png", "EliteBarbarians.png"],
    ["MiniPEKKA.png", "PEKKA.png", "Lightning.png"],
    ["RoyaleRecruits.png", "RoyaleGiant.png", "RoyaleDelivery.png"],
    ["RoyaleHogs.png", "MotherWitch.png", "HogRider.png"],
    ["Guards.png", "RoyaleRecruits.png", "DarkPrince.png"],
    ["Minion.png", "MinionHorde.png", "MegaMinion.png"],
    ["GoblinDemolisher.png", "GoblinMachine.png", "GoblinCage.png"],
    ["BarbarianBarrel.png", "GoblinBarrel.png", "SkeletonBarrel.png"],
    ["SuspiciousBush.png", "Lumberjack.png", "Log.png"],
    ["Archer.png", "Barbarians.png", "Goblin.png"],
    ["Snowball.png", "IceGolem.png", "Freeze.png"],
]

WIN_CONDITIONS = [
    "HogRider.png",
    "Giant.png",
    "Golem.png",
    "PEKKA.png",
    "MegaKnight.png",
    "RoyaleGiant.png",
    "ElectroGiant.png",
    "Miner.png",
    "Balloon.png",
    "Sparky.png",
    "Graveyard.png",
    "Mortar.png",
    "Musketeer.png",
    "Firecracker.png",
    "X-bow.png",
    "Rocket.png",
    "GoblinBarrel.png",
    "GoblinDrill.png",
    "ElixirGolem.png",
    "MotherWitch.png",
    "Princess.png",
    "ArcherQueen.png",
    "GoldenKnight.png",
    "Bandit.png",
    "SpiritEmpress.png",
    "EliteBarbarians.png",
]

DUPLICATES = [
    ["Giant.png", "x3.png"],
    ["Golem.png", "x2.png"],
    ["HogRider.png", "x2.png"],
    ["PEKKA.png", "x2.png"],
    ["MegaKnight.png", "x2.png"],
    ["RoyaleGiant.png", "x2.png"],
    ["ElectroGiant.png", "x2.png"],
    ["Miner.png", "x3.png"],
    ["Balloon.png", "x2.png"],
    ["Sparky.png", "x2.png"],
    ["Firecracker.png", "x4.png"],
    ["Graveyard.png", "x2.png"],
    ["SuspiciousBush.png", "x3.png"],
    ["Knight.png", "x4.png"],
    ["Princess.png", "x6.png"],
    ["Fisherman.png", "x4.png"],
    ["Musketeer.png", "x3.png"],
    ["FlyingMachine.png", "x3.png"],
    ["BabyDragon.png", "x3.png"],
    ["DarkPrince.png", "x3.png"],
    ["MagicArcher.png", "x4.png"],
    ["Witch.png", "x3.png"],
    ["ArcherQueen.png", "x3.png"],
    ["Monk.png", "x3.png"],
    ["EliteBarbarians.png", "x2.png"],
    ["ElixirCollector.png", "x3.png"],
    ["Bowler.png", "x3.png"],
    ["Pheonix.png", "x3.png"],
    ["MegaMinion.png", "x3.png"],
    ["WallBreakers.png", "x2.png"],
    ["IceGolem.png", "x5.png"],
    ["BarbarianHut.png", "x2.png"],
]

BOOST_LIST = [
    "BarbarianHut.png",
    "SpiritEmpress.png",
    "ThreeMusketeers.png",
    "LavaHound.png"
    "BossBandit.png",
    "Goblinstein.png",
    "Monk.png",
    "ArcherQueen.png"
    "SkeletonKing.png",
    "MightyMiner.png",
    "GoldenKnight.png",
    "LittlePrince.png",
    "Rocket.png",
    "Mirror.png",
    "Clone.png",
    "HogRider.png",
    "Xbow.png",
    "Miner.png",
    "GoblinBarrel.png",
    "HealSpirit.png",
]

EXCLUDED_CARDS = [
    "Cannon.png",
    "Tesla.png",
    "BombTower.png",
    "InfernoTower.png",
    "BarbarianHut.png",
    "ElixirCollector.png",
    "GoblinHut.png",
    "Clone.png",
    "RoyaleDelivery.png",
]