TRIPLETS_LIST = [
    ["ElectroSprit.png", "FireSpirit.png", "IceSpirit.png"],
    ["GoblinDrill.png", "Miner.png", "WallBreakers.png"],
    ["GoblinGang.png", "SkeletonArmy.png", "MinionHorde.png"],
    ["BabyDragon.png", "InfernoDragon.png", "ElectroDragon.png"],
    ["Rocket.png", "Fireball.png", "Poison.png"],
    ["Giant.png", "ElectroGiant.png", "RoyaleGiant.png"],
    ["Golem.png", "ElixirGolem.png", "IceGolem.png"],
    ["Mirror.png", "GiantBomber.png", "Clone.png"],
    ["HogRider.png", "RamRider.png", "BattleRam.png"],
    ["ElixirCollector.png", "ElixirGolem.png", "Rage.png"],
    ["DarkPrince.png", "LittlePrince.png", "Prince.png"],
    ["Wizard.png", "ElectroWizard.png", "IceWizard.png"],
    ["Valkyrie.png", "RuneGiant.png", "Berserker.png"],
    ["BombTower.png", "Balloon.png", "Bomber.png"],
    ["Bandit.png", "BossBandit.png", "Rascals.png"],
    ["Zappies.png", "Sparky.png", "Tesla.png"],
    ["RoyaleGhost.png", "SpiritEmpress.png", "Graveyard.png"],
    ["MotherWitch.png", "Witch.png", "NightWitch.png"],
    ["Cannon.png", "FlyingMachine.png", "CannonCart.png"],
    ["Fireball.png", "Earthquake.png", "Tornado.png"],
    ["Void.png", "Vines.png", "GoblinCurse.png"],
    ["Knight.png", "GoldenKnight.png", "MegaKnight.png"],
    ["Archer.png", "ArcherQueen.png", "Arrows.png"],
    ["Barbarians.png", "BarbarianHut.png", "EliteBarbarians.png"],
    ["MiniPEKKA.png", "PEKKA.png", "Lightning.png"],
    ["RoyaleRecruits.png", "RoyaleGiant.png", "RoyaleDelivery.png"],
    ["RoyaleHogs.png", "MotherWitch.png", "HogRider.png"],
    ["Guards.png", "RoyaleRecruits.png", "DarkPrince.png"],
    ["Minion.png", "MinionHorde.png", "MegaMinion.png"],
    ["GoblinDemolisher.png", "GoblinMachine.png", "GoblinCage.png"],
    ["BarbarianBarrel.png", "GoblinBarrel.png", "SkeletonBarrel.png"],
    ["SuspiciousBush.png", "Lumberjack.png", "Log.png"],
    ["Archer.png", "Barbarians.png", "Goblin.png"],
    ["Snowball.png", "IceGolem.png", "Freeze.png"],
]

WIN_CONDITIONS = [
    "HogRider.png",
    "Giant.png",
    "Golem.png",
    "PEKKA.png",
    "MegaKnight.png",
    "RoyaleGiant.png",
    "ElectroGiant.png",
    "Miner.png",
    "Balloon.png",
    "Sparky.png",
    "Graveyard.png",
    "Mortar.png",
    "Musketeer.png",
    "Firecracker.png",
    "X-bow.png",
    "Rocket.png",
    "GoblinBarrel.png",
    "GoblinDrill.png",
    "ElixirGolem.png",
    "MotherWitch.png",
    "Princess.png",
    "ArcherQueen.png",
    "GoldenKnight.png",
    "Bandit.png",
    "SpiritEmpress.png",
    "EliteBarbarians.png",
]

DUPLICATES = [
    ["Giant.png", "x3.png"],
    ["Golem.png", "x2.png"],
    ["HogRider.png", "x2.png"],
    ["PEKKA.png", "x2.png"],
    ["MegaKnight.png", "x2.png"],
    ["RoyaleGiant.png", "x2.png"],
    ["ElectroGiant.png", "x2.png"],
    ["Miner.png", "x3.png"],
    ["Balloon.png", "x2.png"],
    ["Sparky.png", "x2.png"],
    ["Firecracker.png", "x3.png"],
    ["Graveyard.png", "x2.png"],
    ["SuspiciousBush.png", "x3.png"],
    ["Knight.png", "x4.png"],
    ["Princess.png", "x6.png"],
    ["Fisherman.png", "x4.png"],
    ["Musketeer.png", "x3.png"],
    ["FlyingMachine.png", "x3.png"],
    ["BabyDragon.png", "x3.png"],
    ["DarkPrince.png", "x3.png"],
    ["MagicArcher.png", "x4.png"],
    ["Witch.png", "x3.png"],
    ["ArcherQueen.png", "x3.png"],
    ["Monk.png", "x3.png"],
    ["EliteBarbarians.png", "x2.png"],
    ["ElixirCollector.png", "x3.png"],
    ["Bowler.png", "x3.png"],
    ["Pheonix.png", "x4.png"],
    ["MegaMinion.png", "x4.png"],
    ["WallBreakers.png", "x3.png"],
    ["IceGolem.png", "x5.png"]
]

EXCLUDED_CARDS = [
    "Cannon.png",
    "Tesla.png",
    "BombTower.png",
    "InfernoTower.png",
    "BarbarianHut.png",
    "ElixirCollector.png",
    "GoblinHut.png",
    "Clone.png",
    "RoyaleDelivery.png",
]